#!/bin/sh -e

# Common shell script snippets to be used when interacting with openQA
# instances, for example over openqa-cli.

# From openqa-cli JSON output filter and return the id/ids of jobs,
# for example from a query to the 'jobs get' route or the result string of a
# 'jobs post' or 'isos post'
job_ids() {
    jq -r '.ids[]' "$@"
}
