##################################################
# WARNING
# This file is autogenerated by tools/update-deps
# from dependencies.yaml
##################################################

requires 'Data::Dumper';
requires 'FindBin';
requires 'Getopt::Long';
requires 'Mojo::File';
requires 'YAML::PP';

on 'test' => sub {

};

on 'devel' => sub {

};

feature 'coverage', 'coverage for CI' => sub {

};
