#!/bin/bash -e

osc="osc --apiurl https://api.opensuse.org"

for project in $($osc search --project -s 'devel:openQA:Leap:' | grep -o '^devel:openQA:Leap:.*'); do
    for package in $($osc list "$project"); do
        $osc api "/comments/package/$project/$package" | \
            yq -pxml -oy '.comments.comment |= ([] + .) | .comments.comment[].+content' | \
            grep -q "Reason for linking:" || \
            { echo "No reason for $project/$package" >&2; problem=1; }
    done
done

test -z "$problem"
