#!/bin/bash -e

set -o pipefail -o errtrace

source "$(dirname "$0")"/openqa-label-known-issues

to_review=()

print_summary() {
    local to_review_count=${#to_review[@]}
    [[ $to_review_count -eq 0 ]] && return
    local msg="\n\e[1m\e[31m$to_review_count unknown issues to be reviewed:\e[0m"
    for job in "${to_review[@]}"; do
        msg+="\n - $job"
    done
    echo -e "$msg"
}

main() {
    # shellcheck disable=SC2013
    for testurl in $(cat - | sed 's/ .*$//'); do
        label_issue "$testurl"
    done
    print_summary
}

usage() {
    cat << EOF
Usage: echo job_url | $0 [OPTIONS]

Calls 'openqa-label-known-issues' on a list of multiple specified openQA job
URLs.

Options:
 -h, --help         display this help
EOF
    exit "$1"
}

opts=$(getopt -o h -l help -n "$0" -- "$@") || usage 1
eval set -- "$opts"
while true; do
    case "$1" in
        -h | --help) usage 0 ;;
        --)
            shift
            break
            ;;
        *) break ;;
    esac
done

caller 0 > /dev/null || main "$@"
