#!/bin/bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail

# shellcheck source=/dev/null
. "$(dirname "${BASH_SOURCE[0]}")"/_common

main() {
    local rc=0
    # shellcheck disable=SC2013
    for i in $(cat - | sed 's/ .*$//'); do
        openqa-investigate "$i" "$@" || rc=$?
    done
    exit $rc
}

usage() {
    cat << EOF
Usage: echo jobnumber | $0 [OPTIONS]

Triggers 'openqa-investigate' on a list of specified openQA jobs.

Options:
 -h, --help         display this help
EOF
    exit "$1"
}

opts=$(getopt -o h -l help -n "$0" -- "$@") || usage 1
eval set -- "$opts"
while true; do
    case "$1" in
        -h | --help) usage 0 ;;
        --)
            shift
            break
            ;;
        *) break ;;
    esac
done

caller 0 > /dev/null || main "$@"
