#!/bin/bash

# Usage
# echo jobnumber | openqa-investigate

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail

# shellcheck source=/dev/null
. "$(dirname "${BASH_SOURCE[0]}")"/_common

main() {
    local rc=0
    # shellcheck disable=SC2013
    for i in $(cat - | sed 's/ .*$//'); do
        openqa-investigate "$i" "$@" || rc=$?
    done
    exit $rc
}

caller 0 >/dev/null || main "$@"
