#!/bin/bash

# Usage
# echo jobnumber | openqa-investigate

# shellcheck source=/dev/null
source "$(dirname "${BASH_SOURCE[0]}")"/_common

main() {
    local rc=0
    # shellcheck disable=SC2013
    for i in $(cat - | sed 's/ .*$//'); do
        openqa-investigate "$i" "$@" || rc=$?
    done
    exit $rc
}

[[ $0 != "${BASH_SOURCE[0]}" ]] || main "$@"
