#!/bin/bash

set -eo pipefail

# "hook script" intended to be called by openQA instances taking a job ID as
# parameter and forwarding a complete job URL to "openqa-label-known-issues"
# on stdin and all left unknowns to "openqa-investigate"
dir=$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd)
PATH=$dir:$PATH

host="${host:-"openqa.opensuse.org"}"
scheme="${scheme:-"https"}"
host_url="$scheme://$host"

investigate-and-bisect() {
    local rc=0 test
    read -r test
    openqa-investigate "$test" || rc=$?
    [[ "$rc" -eq 142 ]] && return "$rc"
    openqa-trigger-bisect-jobs --url "$test" || rc=$?
    return "$rc"
}

hook() {
    local id="${1:?"Need 'job_id'"}"
    openqa-label-known-issues "$host_url/tests/$id" | sed -n 's/\[\([^]]*\)\].*Unknown issue, to be reviewed.*/\1/p' | investigate-and-bisect
}

caller 0 >/dev/null || hook "$@"
