#!/bin/bash
set -euo pipefail
start="${start:-"01"}"
runs="${runs:-"30"}"
hosts="${1:?"Need 'hosts' to check reboot stability for. Can be multiple"}"
boot_timeout="${boot_timeout:-"600"}"
ping_count="${ping_count:-"30"}"
sleep_time="${sleep_time:-"120"}"

check-one-host() {
    local host=$1
    echo -n "run: $run, $host: ping .. "
    timeout -k 5 "$boot_timeout" sh -c "until ping -c$ping_count $host >/dev/null; do :; done"
    echo -n "ok, ssh .. "
    timeout -k 5 "$boot_timeout" sh -c "until nc -z -w 1 $host 22; do :; done"
    echo -n "ok, uptime/reboot: "
    ssh "$host" "uptime && sudo reboot"
    sleep "$sleep_time"
}

main() {
    for ((run = start; run <= runs; run++)); do
        for host in $hosts; do
            check-one-host "$host" || break
        done || break
    done
}

usage() {
    cat << EOF
Usage: $0 [OPTIONS] HOSTS...

Conducts reboot stability checks against a space-separated list of hosts.

Can be configured additionally with environment variables.

Options:
 -h, --help         display this help
EOF
    exit "$1"
}

opts=$(getopt -o h -l help -n "$0" -- "$@") || usage 1
eval set -- "$opts"
while true; do
    case "$1" in
        -h | --help) usage 0 ;;
        --)
            shift
            break
            ;;
        *) break ;;
    esac
done

caller 0 > /dev/null || main "$@"
