#!/bin/bash
set -euo pipefail
start="${start:-"01"}"
runs="${runs:-"30"}"
hosts="${1:?"Need 'hosts' to check reboot stability for. Can be multiple"}"
boot_timeout="${boot_timeout:-"600"}"
ping_count="${ping_count:-"30"}"
sleep_time="${sleep_time:-"120"}"

check-one-host() {
    local host=$1
    echo -n "run: $run, $host: ping .. "
    timeout -k 5 "$boot_timeout" sh -c "until ping -c$ping_count $host >/dev/null; do :; done"
    echo -n "ok, ssh .. "
    timeout -k 5 "$boot_timeout" sh -c "until nc -z -w 1 $host 22; do :; done"
    echo -n "ok, uptime/reboot: "
    ssh "$host" "uptime && sudo reboot"
    sleep "$sleep_time"
}

main() {
    for ((run = start; run <= runs; run++)); do
        for host in $hosts; do
            check-one-host "$host" || break
        done || break
    done
}

caller 0 >/dev/null || main "$@"
