#!/bin/bash -ex

# Trigger tests on an openQA instance testing openQA itself.
#
# Can be configured by variables.

set -o pipefail

# configuration variables with defaults.
target_host="${target_host:-"openqa.opensuse.org"}"
target_host_proto="${target_host_proto:-"https"}"
dry_run="${dry_run:-"0"}"
tw_openqa_host="${tw_openqa_host:-"https://openqa.opensuse.org"}"
tw_group_id="${tw_group_id:-"1"}"
openqa_cli="${openqa_cli:-"/usr/share/openqa/script/openqa-cli"}"
arch="${arch:-"x86_64"}"
machine="${machine:-"64bit"}"

main() {
    [ "$dry_run" = "1" ] && client_prefix="echo"
    find_latest_published_tumbleweed_image
    trigger
}

find_latest_published_tumbleweed_image() {
    latest_published_tw_build=$(curl "$tw_openqa_host/group_overview/$tw_group_id.json" \
        | jq -r '[.build_results[] | select(.tag.description=="published") | select(.version=="Tumbleweed") | .build] | sort | reverse | .[0]')
    if ! [[ $latest_published_tw_build ]]; then
        echo "Unable to find latest published Tumbleweed build."
        exit 1
    fi
    qcow=$(${openqa_cli} api --host "${tw_openqa_host}" assets get \
        | jq -r "[.assets[] | select(.name | test(\"Tumbleweed-$arch-$latest_published_tw_build-Tumbleweed\\\\@$machine.qcow\"))] | .[0] | .name")
    if ! [[ $qcow ]]; then
        echo "Unable to determine qcow image for Tumbleweed build '$latest_published_tw_build' (for architecture '$arch' and machine '$machine')."
        exit 2
    fi
    if [ "$target_host_proto://$target_host" != "$tw_openqa_host" ]; then
        [ "$qcow" = "" ] && (echo "could not find valid asset" && exit 2)
        url="${tw_openqa_host}/assets/hdd/${qcow}"

        # instead of manual wget it should also work to provide a whitelisted url to openqa as HDD_1_URL which should then download it itself but a first experiment didn't work
        ${client_prefix} wget -c "$url" -O /var/lib/openqa/factory/hdd/"$qcow"
    fi
    # ensure the build tag conforms to coolo's unwritten rules for the openQA dashboard
    build=$(echo "$BUILD_TAG" | sed -e "s/jenkins-trigger-openQA_in_openQA-/:/" -e "s/-/./g")
}

trigger() {
    # prevent host access problem when running within o3 infrastructure
    # where o3 is not reachable over https
    if [ "$target_host" = "openqa.opensuse.org" ]; then
        ARGS="OPENQA_HOST=http://openqa.opensuse.org"
    fi

    ${client_prefix} "${openqa_cli}" api -X POST \
        --host "${target_host_proto}"://"${target_host}" isos \
        VERSION=Tumbleweed \
        DISTRI=openQA FLAVOR=dev BUILD="${build}" \
        ARCH="${arch}" BACKEND=qemu WORKER_CLASS=qemu_x86_64 \
        HDD_1="$qcow" \
        ${ARGS} \
        | tee job_post_response

    JOB_ID=$(sed -n 's/^.*ids => \[\([0-9]\+\)\].*$/\1/p' job_post_response)

    echo "Triggered as: ${target_host_proto}://${target_host}/tests/${JOB_ID}"
}

main
